apiVersion: v1
kind: Pod
metadata:
  name: my-single-pod
  namespace: sample-kube
  labels:
    app: my-pod-selector
    name: my-single-pod
spec:
  containers:
  - name: my-single-pod
    image: streamtank/print-log-only
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
  - name: my-curl
    image: streamtank/devops-samples:ubuntu-with-curl
    tty: true
    resources:
      limits:
        memory: "32Mi"
        cpu: "100m"