apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: sample-kube
spec:
  selector:
    matchLabels:
      app: my-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: my-deployment
    spec:
      containers:
      - name: my-deployment
        image: streamtank/print-log-only:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
