apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: my-daemonset
  namespace: sample-kube
spec:
  selector:
    matchLabels:
      app: my-daemonset
  template:
    metadata:
      labels:
        app: my-daemonset
    spec:
      containers:
      - name: my-daemonset
        image: nginx:1.9.2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
