apiVersion: v1
kind: Service
metadata:
  name: my-statefulset-service
  namespace: sample-kube
spec:
  clusterIP: None
  selector:
    app: my-statefulset
  ports:
  - port: 3000
    targetPort: 3000
