apiVersion: v1
kind: Pod
metadata:
  name: my-single-pod
  namespace: sample-kube
  labels:
    name: my-single-pod
    app: my-pod-selector
spec:
  containers:
  - name: my-single-pod
    image: streamtank/print-log-only
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
  - name: my-curl-pod
    image: ubuntu:18.04
    tty: true
    resources:
      limits:
        cpu: "500m"
        memory: "128Mi"
    command:
      - "bash"
      - "-c"
      - |
        apt-get update && apt-get install -y curl && bash